### PR TITLE
ANTSDR for openwifi-hw

### PR DESCRIPTION
**Pull request by MicroPhase**
We add a new sdr hardware for openwifi-hw, the new platform is at the folder of boards/antsdr. These is mainly based on adrv9364z7020. In our SDR platform, there is 4 RF switch in the RF  front end, in this fpga design, we let the RF switch to the fixed vaule, which will only let the frequency at 3G~6GHz non-isolated, this could be improved in future work.

### CODE REVIEW

**Comment by JiaoXianjun** [comment]
Hello,

First all, thanks for making the pull request!

Reviewing is ongoing, so I will leave comments from time to time here. You don't need to take any further action for now, until I finish all the reviewing.

The basic driven idea is to make minimum change, or to only make necessary change. In this way, we keep the same/similar structure/content for different hardware platform, and make it easier for people to understand the difference between the new and old hardware.

1. Regarding prepare_adi_board_ip.sh, so maybe you could put antsdr into the same line of adrv9364z7020, because they point to the same directory? For example:
```
if [ "$BOARD_NAME" == "adrv9364z7020" ] || [ "$BOARD_NAME" == "antsdr" ]; then
```

2. I realize that the ccbob_constr.xdc in boards/antsdr/src/ is the same as it in adi-hdl/projects/adrv9364z7020/common/, so maybe you could remove it from boards/antsdr/src/, and also change the ccbob_constr.xdc line of boards/antsdr/openwifi.tcl back accordingly?

**Comment by JiaoXianjun** [comment]
Hello

I have generated the antsdr bitstream successfully! The modifications seem OK for build.

Regarding the antsdr README, it is written in good way. Thanks! But I think there is no essential difference from our original README, so I would prefer not to use a dedicated antsdr README. Instead, in the future I will add antsdr to the single README.

I have created https://github.com/open-sdr/openwifi-hw/tree/antsdr in our repo, and I suggest we proceed like this:

1. Would you please make a new pull request towards antsdr branch (our repo) after adopting my previous comments (if you agree on my previous comments, or any other proposals if not?)
2. I will make pull request towards antsdr branch (our repo) after modifying our original README to include antsdr, and ask you to review.
3. In the future, if I have chance to test the antsdr at our side and everything is OK, I will merge antsdr branch to master.

In the future I propose we work together like this:

1. The antsdr branch in our repo will stay to receive your future pull requests, because I believe you will have future hardware/FPGA related fixing/modifications/upgrading. We do review and necessary change together in antsdr branch (our repo).
2. If the test is OK at our side, I will merge the antsdr branch to the master (in our repo).

**Comment by black-pigeon** [comment]
Ok, I will handle this. The **ccbob_constr.xdc**  in boards/antsdr/src/ is not the same as it in adi-hdl/projects/adrv9364z7020/common/. So I add it into the boards/antsdr/src folder. 
I will make a new pull request to the original antsdr branch.

**Comment by JiaoXianjun** [comment]
Indeed, ccbob_constr.xdc is different. I compared the wrong file.

**Pull request closed without merging**
